# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: name-tests-test
        exclude: ^src/tests/fixtures/
        args: ["--pytest-test-first"]
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
        -   id: reorder-python-imports
            exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
            args: [--py39-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3.11
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        args: [--explicit-package-bases, --ignore-missing-imports]
        exclude: ^samples/|^files/
-   repo: https://github.com/sbrunner/hooks
    rev: 1.0.0
    hooks:
    -   id: copyright
        exclude: (^samples/|^files/|.*\.yaml|Dockerfile.*|LICENSE|.*\.md|\.gitignore|.*\.toml|\.flake8)
    -   id: copyright-required
        exclude: (^samples/|^files/|.*\.yaml|Dockerfile.*|LICENSE|.*\.md|\.gitignore|.*\.toml|\.flake8)
