FROM python:3.11-slim

ENV IS_GITHUB_ACTION=true

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN pip install -e .[dev]

CMD ["pytest"]
