name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IS_GITHUB_ACTION: true

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1

    - name: Test with pytest
      run: |
        pytest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: cloudtruth/dynamic-importer
