name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build test image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.test
        platforms: linux/amd64
        push: false
        tags: cloudtruth/dynamic-importer-test:latest

    - name: Test image
      uses: addnab/docker-run-action@v3
      with:
        image: cloudtruth/dynamic-importer-test:latest
        options: -v ${{ github.workspace }}:/app -e IS_GITHUB_ACTION=true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: cloudtruth/dynamic-importer
