name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build test image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.test
        load: true
        platforms: linux/amd64
        tags: dynamic-importer-test:latest

    - name: Test image
      uses: addnab/docker-run-action@v3
      with:
        image: dynamic-importer-test:latest
        options: -v ${{ github.workspace }}:/app
        run: pytest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: cloudtruth/dynamic-importer
