#
# Copyright (C) 2024 CloudTruth, Inc.
# All Rights Reserved
#
---
name: release
on:
  release:
    types:
      - published

env:
  BUILD_TAG: ${{ github.event.release.tag_name }}
  DOCKER_REPO: cloudtruth/dynamic-importer

permissions:
  contents: read    # required for actions/checkout

jobs:
  build-containers:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - uses: actions/checkout@v3

      - name: Set docker login environment from cloudtruth
        uses: cloudtruth/configure-action@v2
        with:
          apikey: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "production"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.BUILD_TAG }}
